alphapapa/ement.el

ement-room.el

Fixes #16.
* `pop-to-buffer' seems to deactivate the buffer's input method.
This meant that users had to explicitly switch to the correct input
method by pressing C-\.
* Without explicitly disabling the input method of the minibuffer,
every minibuffer command inherited the room's input method.  This is
not the desired behaviour.  The solution seems to be to explicitly
deactivate the minibuffer's input method before calling
`abort-recursive-edit'.

Fix: (ement-room-compose-from-minibuffer) Inherit minibuffer's input method properly

---

ement-room.el

The spec for calculating room names is, I think, confusingly specified.
I believe it should not be considered sequentially because subparagraph iii can't be reached if you consider i first.
This change re-orders the branches so that it will check for rooms where the total member count is <= 0 before considering the other possibilities.

Fix: (ement-room--room-display-name) check for empty room first

---

README.org

It seems a botched edit changed the example connection command. I just restored the original version.

Correcting pantalaimon connection command

---

README.org
ement-room.el
ement.el

This simply swaps the argument order to the right one

Fix: (ement-room-sync) Correct argument order

---

README.org
ement-notify.el

Use a 500ms timeout instead of the standard 25 seconds so that loading
ement-notify.el doesn't stall for ages when something DBUS is wonky.
This fixes #98.

Fix: (ement-notify-dbus-p) dbus-ping with timeout

---

ement-room.el

If `browse-url-handlers` is not defined then fall back to using `browse-url-browser-function`.

Emacs 27 compatibility fix #90

---

README.org
ement.el

Closes #66
Confirmed working with a Conduit server and with a Synapse server

Fix login for non-Synapse servers

---

README.org
ement-room.el

Continuation of #39.  I've been using this patch for a while now and no issues so far but note that I don't have images enabled for anything other messages (no avatars, room images, etc.) so there may be other issues that I do not know of.

(ement-room-image-keymap) Inherit from image-map

---

README.org
ement-room.el

This is very similar to the m.file handler (which would mostly work for videos as well), and is also missing support for thumbnails (however the events I'm seeing don't contain those anyway).
In comparison to ement-room--format-m.file this handler uses content.body as the caption instead of content.filename (which m.video doesn't contain, while m.file does have body). Also the video resolution is shown (<width>x<height>).

Add basic support for m.video events

---

README.org
ement-room.el

Propertize the spaces in the widget's format string to hide them. We could, alternatively, use a zero-width space... but that won't work on a TTY.
This is a bit of a hack but it looks much nicer.

Fix: avoid spurious indent in room membership changes

---

README.org
ement-room.el

Previously, this would attempt to retrieve old events whenever scrolling did nothing. Even when we were at the bottom of the buffer.
(I can update the changelog, but I don't think this warrants it)

fix: only autoload when scrolling past the top

---

README.org
ement-room.el

Refactor `ement-room-image-show` to `ement-room-image-show` and `ement-room-image-show-mouse`. Ditto for `-image-scale-`. Then bind RET/M-RET to these new commands.
NOTE: this renames `ement-room-image-show` to `ement-room-image-show-mouse` for consistency (breaking).
If you'd like to avoid the breaking change, I can rename these functions to `-at-point` and `-mouse`, and turn the existing versions into aliases.

Support RET/M-RET for viewing/scaling images

---

README.org
ement-lib.el

Parse actions according to https://spec.matrix.org/v1.7/client-server-api/#actions, allowing for 0 or more actions in any order.
fixes #181

Fix room list display with empty notification actions

---

README.org

Hi, this PR adds a static link to `emacs-ement` in the README that points to the Guix package search.

Add Guix package search link

---

README.org
ement-room.el

This makes it easy to, e.g., zoom the image (and prevents any attempts to edit it, add text to the buffer, etc.).

Enable image-mode when displaying images in a new buffer

---

README.org
ement-room.el

Only insert a sender header if the previous message is from a different sender, and there is no sender header between the current message and the previous message.
While the previous version of this function explicitly skipped the read marker, this version searches for known events (messages and sender headers), skipping everything it doesn't understand. This should make it robust to adding new events, widgets, etc.
fixes #157

Fix sender header insertion with respect to membership changes

---

ement-room-list.el
ement.el

See <https://github.com/alphapapa/ement.el/issues/256>.

Cache visibility data concisely

---

README.org
ement-room.el

Very similar to the m.video handler (which is very similar to the m.file handler).
Again uses the message body as the title, and displays both audio duration and size.

Add basic support for m.audio events

---

README.org
ement-room.el

Don't read the reaction from the user if it can't be used.

Fix: (ement-room-send-reaction) Bail out early when there's no event at point

---

README.org
ement-lib.el
ement-room.el

- Fix #241
- Change: (ement-room-browse-url) Use `read-multiple-choice`.
- Add mouse support (by side-effect).
- Fix: (ement-room-browse-url) Avoid recursive call.
- Add: (ement--read-multiple-choice) Wrapper for `read-multiple-choice` to bypass the hard-coded multi-column formatting in the help buffer (as it tends to wrap poorly).

Fix: Non-obvious "Join it, or load link with browser?" prompt

---

README.org
ement-lib.el

Fix: (ement--format-body-mentions) Link usernames following newlines

---

README.org
ement-room.el

When the format contains newlines, only the line containing %W is used to establish the width of the wrap-prefix.  Previously the widths of any preceding lines were included as well.
Closes #182.

Fix: (ement-room--format-message) %W considers only the current line

---

README.org
ement-room.el

Support variable-pitch face for plain text messages

---

ement-room.el

A handful of bug fixes and enhancements following on from https://github.com/alphapapa/ement.el/pull/270.
* Use a window-parameter for the compose buffer window auto-height cache
The old system was usually fine in practice, but this is correct/better.
* Prevent unwanted resizing when cycling through buffers in a window
This eliminates a potential pain point, whereby the window resizing might easily be unwanted.
* Support an option for deleting compose buffer windows without them being dedicated
This is a way to get the "old" behaviour back (when the windows were not dedicated by default).
* Eliminate the timer-triggered resize from ement-room-compose-buffer-window-buffer-change-handler
This no longer seemed necessary, so I took the opportunity to simplify things by removing it.
* Improved …

Improvements and bug fixes for the compose buffer enhancements (part 2)

---

README.org
ement-room.el

I think this is ready to merge (and addresses #199), but note that it offers you the Emacs 29 emoji commands as options even if you don't have them. Likewise it binds them to keys. The docstring do mention you need Emacs 29 to use them, but maybe you'd want them to not even appear.

Configurable emoji reaction picker

---

ement-room.el

There are mode line constructs in the mode-name for `ement-room-mode`, so this change works around [Emacs bug#68600](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=68600).
Also declare `visual-line-mode` value in the :options list, as that value is added to this hook as standard.

Tidy: Use custom docstring for ement-room-mode-hook

---

README.org

Per `(info "(org)Escape Character")` I've introduced a zero-width space before the closing paren in "(while writing in minibuffer: ~C-c '~​)" in order to achieve the correct formatting.  This can be visualised using `(set-face-background 'glyphless-char "red")`.
I've substituted` S-<return>` everywhere that `S-RET` appeared, as the latter isn't a valid representation.

Docs: Update readme

---

README.org
ement-room.el

Debian testing
29.1, installed as a package from Debian testing.
emacs --fg-daemon
Gui frame, pgtk
0.13, as a package from Debian testing
Pressed enter in the room list buffer to open a room buffer
It took slightly over 7 minutes (with Emacs using 100% cpu for the whole time) to open the buffer for a room with 221 members. The room is bridged to IRC, so it sees a lot of joining and leaving (I assume processing these is the problem).
Most rooms only take a few seconds to open. Getting below a minute would already be quite useful.
_No response_
Adding a per-room or global option to not process all of the membership changes at buffer open time would be a workaround.
I wonder if this is actually necessary at all, though. If I press C-g while this is happening the buffer opens just fine, it …

Opening buffers whose rooms have very large numbers of adjacent membership events can be very slow

---

README.org
ement-room.el

Strip the `line-prefix` and `wrap-prefix` text properties which are used when formatting certain Matrix events, but which should not be copied into other buffers.
This is especially relevant when using `%W` in `ement-room-message-format-spec` to provide indentation when wrapping message body lines.
With this filter configured, we can copy text from an ement room and yank it into another buffer without this formatting being included.  See also `filter-buffer-substring`:
> For example, major or minor modes can use `filter-buffer-substring-function' to exclude text properties that are special to a buffer, and should not be copied into other buffers.

Change: (ement-room-mode) Set `filter-buffer-substring-function'

---

README.org
ement-room.el

These definitions come after defgroup ement-room-prism, so they need an explicit :group argument.

Fix: Customize group for ement-room-mode-hook, ement-room-self-insert-mode

---

ement-room-list.el
ement-tabulated-room-list.el

The byte-compiler of Emacs 31 has started to warn about these.

Fix: Fix inheritance in face definitions

---

README.org
ement-room-list.el
ement-room.el
ement-tabulated-room-list.el
ement.el

Each face now belongs to one of the following new groups:
- `ement-room-faces` (sub-group of `ement-room`)
- `ement-room-list-faces` (sub-group of `ement-room-list`)
- `ement-tabulated-room-list-faces` (sub-group of `ement-tabulated-room-list`)
Additionally, each of those new groups is also a sub-group of another new group `ement-faces` (which is parent to only the three 'faces' sub-groups).
You can therefore navigate to each list of faces from either the customize group the faces used to belong to, or via the new `ement-faces` container.
Also:
- Delete duplicate defgroup ement-room-list.
- Tweak phrasing for defgroup ement-tabulated-room-list for consistency with ement-room-list.

Add: Customize groups for Ement faces

---

README.org
ement-room.el

@phil-s What do you think about this as a new default?  
I had considered implementing a button to toggle the visibility of redacted messages, but I'm not sure the complexity would be worth it.  This seems like a good and simple default behavior to protect users from seeing unpleasant content that has since been redacted, while still allowing it to be overridden if necessary.

Add: (ement-room-hide-redacted-message-content) New option

---

README.org
ement-room.el

Add a function for downloading media, and use it as the default action for m.audio, m.file and m.video.
Now that authenticated media is the expected situation opening these as links in an external browser no longer works, so try this instead.
"Open in the chosen application for this mime type" would be nice as well, but based on looking at the way Gnus does this it seems harder than expected. Perhaps there is something I don't understand here..

Support downloading media
